# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hugo Penna
email: site@hugopenna.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog pessoal de Hugo Penna, aqui escrevo sobre o que vier à cabeça,aventuras, devaneios, empreendedorismo, programação.
  Efim, é tudo mesmo!

baseurl: "" # the subpath of your site, e.g. /blog
url: hugopenna.com
twitter_username: hugopenna
github_username:  hugopenna
linkedin_username: hugopenna


sitemap: True

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%d %b %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
lang: "pt-br"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     text: English
#
#   - lang: fr
#     img: https://www.countryflags.io/fr/flat/64.png
#     text: Franch
#
#   - lang: zh-CN
#     img: https://www.countryflags.io/cn/flat/64.png
#     text: Chinese(Simple)
#
#   - lang: zh-TW
#     img: https://www.countryflags.io/tw/flat/64.png
#     text: Chinese(Traditional)
#
#   - lang: ja
#     img: https://www.countryflags.io/jp/flat/64.png
#     text: Japan
#
#   - lang: ko
#     img: https://www.countryflags.io/kr/flat/64.png
#     text: Korean
#
#   - lang: ru
#     img: https://www.countryflags.io/ru/flat/64.png
#     text: Russia

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

#header_pages:
#    - /index.html
#    - /about.html
#    - archives.html
#    - categories.html
#    - tags.html

# Build settings
theme: jekyll-theme-yat
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
